In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [8]:
df=pd.read_csv("Healthcare-Diabetes.csv")
df

Id  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0        1            6      148             72             35        0  33.6   
1        2            1       85             66             29        0  26.6   
2        3            8      183             64              0        0  23.3   
3        4            1       89             66             23       94  28.1   
4        5            0      137             40             35      168  43.1   
...    ...          ...      ...            ...            ...      ...   ...   
2763  2764            2       75             64             24       55  29.7   
2764  2765            8      179             72             42      130  32.7   
2765  2766            6       85             78              0        0  31.2   
2766  2767            0      129            110             46      130  67.1   
2767  2768            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.627   50        1  
1                        0.351   31        0  
2                        0.672   32        1  
3                        0.167   21        0  
4                        2.288   33        1  
...                        ...  ...      ...  
2763                     0.370   33        0  
2764                     0.719   36        1  
2765                     0.382   42        0  
2766                     0.319   26        1  
2767                     0.547   25        0  

[2768 rows x 10 columns]

In [9]:
df.describe()

Id  Pregnancies      Glucose  BloodPressure  SkinThickness  \
count  2768.000000  2768.000000  2768.000000    2768.000000    2768.000000   
mean   1384.500000     3.742775   121.102601      69.134393      20.824422   
std     799.197097     3.323801    32.036508      19.231438      16.059596   
min       1.000000     0.000000     0.000000       0.000000       0.000000   
25%     692.750000     1.000000    99.000000      62.000000       0.000000   
50%    1384.500000     3.000000   117.000000      72.000000      23.000000   
75%    2076.250000     6.000000   141.000000      80.000000      32.000000   
max    2768.000000    17.000000   199.000000     122.000000     110.000000   

           Insulin          BMI  DiabetesPedigreeFunction          Age  \
count  2768.000000  2768.000000               2768.000000  2768.000000   
mean     80.127890    32.137392                  0.471193    33.132225   
std     112.301933     8.076127                  0.325669    11.777230   
min       0.000000     0.000000                  0.078000    21.000000   
25%       0.000000    27.300000                  0.244000    24.000000   
50%      37.000000    32.200000                  0.375000    29.000000   
75%     130.000000    36.625000                  0.624000    40.000000   
max     846.000000    80.600000                  2.420000    81.000000   

           Outcome  
count  2768.000000  
mean      0.343931  
std       0.475104  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

In [10]:
df.isnull().sum()

Id                          0
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [11]:
df.dtypes

Id                            int64
Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [12]:
df["Outcome"].value_counts()

0    1816
1     952
Name: Outcome, dtype: int64

In [15]:
features=df.iloc[:,1:-1]
labels=df.iloc[:,[-1]]
display(features,labels)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               6      148             72             35        0  33.6   
1               1       85             66             29        0  26.6   
2               8      183             64              0        0  23.3   
3               1       89             66             23       94  28.1   
4               0      137             40             35      168  43.1   
...           ...      ...            ...            ...      ...   ...   
2763            2       75             64             24       55  29.7   
2764            8      179             72             42      130  32.7   
2765            6       85             78              0        0  31.2   
2766            0      129            110             46      130  67.1   
2767            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  
0                        0.627   50  
1                        0.351   31  
2                        0.672   32  
3                        0.167   21  
4                        2.288   33  
...                        ...  ...  
2763                     0.370   33  
2764                     0.719   36  
2765                     0.382   42  
2766                     0.319   26  
2767                     0.547   25  

[2768 rows x 8 columns]

Outcome
0           1
1           0
2           1
3           0
4           1
...       ...
2763        0
2764        1
2765        0
2766        1
2767        0

[2768 rows x 1 columns]

In [16]:
train_x,test_x,train_y,test_y=train_test_split(features,labels,stratify=labels,test_size=0.2)
display(train_x,train_y,test_x,test_y)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1691            2      119              0              0        0  19.6   
2478            6      183             94              0        0  40.8   
861             4      134             72              0        0  23.8   
2593            8       65             72             23        0  32.0   
1689            2      134             70              0        0  28.9   
...           ...      ...            ...            ...      ...   ...   
688             1      140             74             26      180  24.1   
683             4      125             80              0        0  32.3   
2051            1       88             30             42       99  55.0   
1535            1       93             70             31        0  30.4   
684             5      136             82              0        0   0.0   

      DiabetesPedigreeFunction  Age  
1691                     0.832   72  
2478                     1.461   45  
861                      0.277   60  
2593                     0.600   42  
1689                     0.542   23  
...                        ...  ...  
688                      0.828   23  
683                      0.536   27  
2051                     0.496   26  
1535                     0.315   23  
684                      0.640   69  

[2214 rows x 8 columns]

Outcome
1691        0
2478        0
861         1
2593        0
1689        1
...       ...
688         0
683         1
2051        1
1535        0
684         0

[2214 rows x 1 columns]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1120            3       61             82             28        0  34.4   
2745            2       99             52             15       94  24.6   
1973            3      187             70             22      200  36.4   
2192            0      138              0              0        0  36.3   
450             1       82             64             13       95  21.2   
...           ...      ...            ...            ...      ...   ...   
470             1      144             82             40        0  41.3   
1136            3       81             86             16       66  27.5   
1671            2      139             75              0        0  25.6   
1590            3       61             82             28        0  34.4   
193            11      135              0              0        0  52.3   

      DiabetesPedigreeFunction  Age  
1120                     0.243   46  
2745                     0.637   21  
1973                     0.408   36  
2192                     0.933   25  
450                      0.415   23  
...                        ...  ...  
470                      0.607   28  
1136                     0.306   22  
1671                     0.167   29  
1590                     0.243   46  
193                      0.578   40  

[554 rows x 8 columns]

Outcome
1120        0
2745        0
1973        1
2192        1
450         0
...       ...
470         0
1136        0
1671        0
1590        0
193         1

[554 rows x 1 columns]

In [23]:
cross_val_score(DecisionTreeClassifier(criterion="entropy"),train_x,train_y,cv=5)

array([0.97065463, 0.9751693 , 0.97742664, 0.98871332, 0.9638009 ])

In [32]:
cross_val_score(KNeighborsClassifier(n_neighbors=7),train_x,train_y,cv=5)

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples

array([0.79458239, 0.81038375, 0.79458239, 0.80361174, 0.80316742])

In [31]:
cross_val_score(SVC(kernel= "poly"),train_x,train_y,cv=5)

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

array([0.77426637, 0.77878104, 0.77200903, 0.78329571, 0.78506787])

In [22]:
cross_val_score(RandomForestClassifier(),train_x,train_y,cv=5)

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was pa

array([0.98419865, 0.97968397, 0.98419865, 0.98419865, 0.96153846])

In [33]:
model=KNeighborsClassifier(n_neighbors=7)

In [34]:
model.fit(train_x,train_y)

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=7)

In [35]:
model.score(test_x,test_y)

0.8086642599277978

In [36]:
model.predict([[3,187,70,22,200,36.4,0.408,36]])

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [37]:
import joblib

In [38]:
joblib.dump(model,"knn_C")

['knn_C']

In [ ]:
joblib.load("Knn")